/* Esquema da tabela! */
CREATE TABLE "TWEET" (
  "ID" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  "IDTWEET" int(100) NOT NULL,
  "DATA" char(255) NOT NULL,
  "USUARIO" char(255) NOT NULL,
  "HASHTAGS" char(255) NOT NULL,
  "RETWEETS" int(100) NOT NULL,
  "FAVORITOS" int(100) NOT NULL,
  "TWEET" char(255) NOT NULL
);
